sudo: required
services:
- docker
before_install:
- docker pull arxivvanity/engrafo:latest
script:
- script/test
deploy:
  provider: script
  script:
    script/install_helm labs &&
    script/publish_chart &&
    script/deploy readability labs
  skip_cleanup: true
  on:
    branch: deployment
